server:
  port: 8762

spring:
  application:
    name: service-demo

eureka:
  instance:
    instance-id: eurekamaster.com:8762/service-demo
  client:
    serviceUrl:
      defaultZone: http://eurekamaster.com:8888/eureka/