server:
  port: 8762

spring:
  application:
    name: microservice-demo
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekamaster.com:8888/eureka/






