server:
  port: 8764
eureka:
  instance:
    instance-id: microservice:pc:8764
    hostname: eurekamaster.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekamaster.com:8888/eureka


spring:
  application:
      name: microservice-pc
