server:
  port: 8888
eureka:
  instance:
    hostname: eurekamaster.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eurekamaster.com:8888/eureka/
  server:
    enable-self-preservation: false




spring:
  application:
    name: eureka-server