# ecah change one spring application file name
spring:
  profiles:
    active: slave

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

