server:
  port: 8766

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuzhitao524/spring-cloud-config/
          password:
          search-paths: repo-demo
          username: