server:
  port: 8766

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuzhitao524/spring-cloud-config/
          password:
          search-paths: repo-demo
          username:


eureka:
  instance:
    hostname: eurekamaster.com
    instance-id: config-server:8766
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekamaster.com:8888/eureka


